### ISSUE TITLE
v3.1.1 and 3.1.2 error deprecated ! Downgrade to v3.1.0

### ISSUE THREAD

**Issue by corentin35000** [capacitor-community/bluetooth-le#634] opened 2024-03-08 14:27 UTC
Hello,

Unable to open .apk on Android device, message: Package parsing problem.

Run command : gradlew assembleRelease

Ouputs : 

``
> Task :capacitor-community-bluetooth-le:compileReleaseKotlin
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/BluetoothLe.kt:187:40 'enable(): Boolean' is deprecated. Deprecated in Java
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/BluetoothLe.kt:198:40 'disable(): Boolean' is deprecated. Deprecated in Java
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:132:22 This declaration overrides deprecated member but not marked as deprecated itself. This deprecation won't be inherited in future releases. Please add @Deprecated annotation or suppress. See https://youtrack.jetbrains.com/issue/KT-47902 for details
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:140:19 'onCharacteristicRead(BluetoothGatt!, BluetoothGattCharacteristic!, Int): Unit' is deprecated. Deprecated in Java
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:143:43 'getter for value: ByteArray!' is deprecated. Deprecated in Java
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:187:22 This declaration overrides deprecated member but not marked as deprecated itself. This deprecation won't be inherited in future releases. Please add @Deprecated annotation or suppress. See https://youtrack.jetbrains.com/issue/KT-47902 for details
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:195:19 'onCharacteristicChanged(BluetoothGatt!, BluetoothGattCharacteristic!): Unit' is deprecated. Deprecated in Java
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:197:39 'getter for value: ByteArray!' is deprecated. Deprecated in Java
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:216:22 This declaration overrides deprecated member but not marked as deprecated itself. This deprecation won't be inherited in future releases. Please add @Deprecated annotation or suppress. See https://youtrack.jetbrains.com/issue/KT-47902 for details
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:224:19 'onDescriptorRead(BluetoothGatt!, BluetoothGattDescriptor!, Int): Unit' is deprecated. Deprecated in Java
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:228:39 'getter for value: ByteArray!' is deprecated. Deprecated in Java
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:365:40 'getParcelableExtra(String!): T?' is deprecated. Deprecated in Java
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:502:28 'setter for value: ByteArray!' is deprecated. Deprecated in Java
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:504:41 'writeCharacteristic(BluetoothGattCharacteristic!): Boolean' is deprecated. Deprecated in Java
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:564:24 'setter for value: ByteArray!' is deprecated. Deprecated in Java
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:565:45 'writeDescriptor(BluetoothGattDescriptor!): Boolean' is deprecated. Deprecated in Java
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:633:24 'setter for value: ByteArray!' is deprecated. Deprecated in Java
w: file:///C:/Users/Corentin.recanzone/Desktop/Biosency/bora-connect-for-home/node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt:634:41 'writeDescriptor(BluetoothGattDescriptor!): Boolean' is deprecated. Deprecated in Java
``

**Comment by pwespi** [comment] 2024-04-06 08:10
closing as duplicate of #551. 

> We have changed the code to use the new Android methods from API level 33 for Android >= 13. However the old code is still there as well to support older devices. Therefore the deprecation warnings will still appear until we can remove the old code, which will take some time.

**Closed by pwespi** 2024-04-06 08:10 UTC
Labels: bug
